### ISSUE TITLE
Bisenet v2 does not work when using the cityscape dataset, the result has always been NAN, and using my own dataset miou is only 0.49

### ISSUE THREAD

**Issue by iloyu** [MaybeShewill-CV/bisenetv2-tensorflow#10]
![image](https://user-images.githubusercontent.com/11597243/84263466-1e2aa280-ab52-11ea-8867-02e21d3c464e.png)
![image](https://user-images.githubusercontent.com/11597243/84263558-487c6000-ab52-11ea-8e24-531606fa7f10.png)

**Comment by MaybeShewill-CV** [comment]
@iloyu 1. Make sure you have correctly generated the tensorflow records 2. Make sure you have the same tf version as mine. 3.Use eval scripts to evaluate the miou on your test dataset:)

**Comment by iloyu** [comment]
I have advanced tensorflow version，is that matters？
![image](https://user-images.githubusercontent.com/11597243/84343009-9be5c100-abd9-11ea-9c64-713488278e54.png)

**Comment by iloyu** [comment]
![image](https://user-images.githubusercontent.com/11597243/84343063-bc158000-abd9-11ea-967e-b4320ea16b5a.png)
in the log ,it says generate ok!

**Comment by MaybeShewill-CV** [comment]
@iloyu The different version of tf may cause the problem. Such a problem is not supposed to occur if you have the same version of tf as mine:)

**Comment by zhuyan288** [comment]
hi, can you help me ?  i hava the same tf version(1.12.0), but it still cause train loss nan . my ops are simple:
1. download the code.
2. python ./data/example_dataset/cityscapes/image_file_index/make_image_file_index.py
3.  modify the config file:
DATASET:
    DATA_DIR: './data/example_dataset/cityscapes'
    IMAGE_TYPE: 'rgb'  # choice rgb or rgba
    NUM_CLASSES: 19
    TEST_FILE_LIST: './data/example_dataset/cityscapes/image_file_index/test.txt'
    TRAIN_FILE_LIST: './data/example_dataset/cityscapes/image_file_index/train.txt'
    VAL_FILE_LIST: './data/example_dataset/cityscapes/image_file_index/val.txt'
    ...
4. python tools/cityscapes/make_cityscapes_tfrecords.py
5. CUDA_VISIBLE_DEVICES="2, 3" python [tools/cityscapes/train_bisenetv2_cityscapes.py

then the train loss is nan ,miou is nan too.
thanks.
