### ISSUE TITLE
Params

### ISSUE THREAD

**Issue by sxlyiyiyi** [MaybeShewill-CV/bisenetv2-tensorflow#11]
Could you tell me how many params about your job of the BiseNet v2

**Comment by MaybeShewill-CV** [comment]
@sxlyiyiyi Maybe https://github.com/MaybeShewill-CV/bisenetv2-tensorflow/blob/81f3855e457f7f294d543490d6f1d40b5534c764/tools/timeprofile_bisenetv2.py#L291-L302 may satisfy.
