### ISSUE TITLE
suggest to isolate pretrained model with codes

### ISSUE THREAD

**Issue by mychina75** [MaybeShewill-CV/bisenetv2-tensorflow#13]
hi，
预训练的模型放在代码库里，git clone的时候非常慢...
建议单独提供下载链接...
现在同步代码太难了

多谢~

**Comment by MaybeShewill-CV** [comment]
@mychina75 是吗 我是看模型都不大就偷懒直接全部上传了==! 下来单独提供个链接吧:)

**Comment by MaybeShewill-CV** [comment]
@mychina75 更新下repo 新的readme里面有提供预训练模型的下载链接:)
