### ISSUE TITLE
Explanation of the data augmentation strategy

### ISSUE THREAD

**Issue by lev1khachatryan** [MaybeShewill-CV/bisenetv2-tensorflow#14]
Hi,

Could you explain the data augmentation strategy, what the following parameters mean:
    FIX_RESIZE_SIZE: [720, 720] # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.75  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling

If you fix crop size for training and evaluating (by TRAIN_CROP_SIZE and EVAL_CROP_SIZE parameters), then why do you need above parameters ?

**Comment by MaybeShewill-CV** [comment]
@lev1khachatryan I believe the comment has been pretty clear. Those params are used when you apply resize with different strategy (eg. rangescaling and stepscaling). Cropping operation was applied when the image was resized properly:)
