### ISSUE TITLE
Errors in tools/cityscapes/test_bisenetv2_cityscapes.py

### ISSUE THREAD

**Issue by yakubota** [MaybeShewill-CV/bisenetv2-tensorflow#15]
When I use this command to test, I got error:
The following error occurred. Please point out what needs to be fixed.

python tools/cityscapes/test_bisenetv2_cityscapes.py --weights_path ./model/cityscapes/bisenetv2/cityscapes.ckpt.data-00000-of-00001 --src_image_path ./data/test_image/test_01.png

Error:
2020-06-26 22:22:14.113271: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-06-26 22:22:14.113348: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "tools/cityscapes/test_bisenetv2_cityscapes.py", line 20, in <module>
    from bisenet_model import bisenet_v2
ImportError: No module named 'bisenet_model'

The weight files and input image files are located in the following paths.
--weights_path ./model/cityscapes/bisenetv2/cityscapes.ckpt.data-00000-of-00001
--src_image_path ./data/test_image/test_01.png

**Comment by MaybeShewill-CV** [comment]
@yakubota Add the root path you the repo to PYTHONPATH env varas:)

**Comment by yakubota** [comment]
Could you give me a little more detail? I don't understand the method you have taught me.
Also, I would like to know if there are any websites related to this method.

**Comment by MaybeShewill-CV** [comment]
@yakubota You may google how to solve it. It's not a very difficult problem:)

**Comment by yakubota** [comment]
I understand the solution. Thank you very much for your kind advice.

**Comment by MaybeShewill-CV** [comment]
@yakubota Welcome:)
