### ISSUE TITLE
Questions about annotations method and train.py

### ISSUE THREAD

**Issue by yakubota** [MaybeShewill-CV/bisenetv2-tensorflow#17]
I have two questions.
Which method did you use to annotate? In my annotation method (VGG Image Annotator ), the "json" file could be created, but the image after annotation "...gtFine_ The "labelTrainIds.png" could not be created.

When I run it, I get the following error.
From the downloaded file "cityscapes_bisenetv2.yaml" Only the path to the dataset has changed. The dataset uses the downloaded files; the rest of the dataset remains unchanged.
The dataset uses the file you downloaded. (\data\example_dataset\cityscapes)

python tools/cityscapes/train_bisenetv2_cityscapes.py
Error:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 2097152 values, but the requested shape has 262144
         [[{{node Reshape_1}}]]
         [[graph_input_node/val_IteratorGetNext]]

**Comment by MaybeShewill-CV** [comment]
@yakubota 1. I did not annotate images by my own. The cityscapes dataset have well annotated images. If you do not know how to generated the annotated images you refer to https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/createTrainIdLabelImgs.py or https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/json2labelImg.py which may help you. 2. As for the error you mentioned here make sure you have correctly generate the training images and their corresponding lable images first. Then use the tool https://github.com/MaybeShewill-CV/bisenetv2-tensorflow/blob/master/data/example_dataset/cityscapes/image_file_index/make_image_file_index.py to generate the training index file. Finally make sure you have set the dataset dir path in cityscapes_bisenetv2.yaml file properly:)

**Comment by yakubota** [comment]
Thank you for your thoughtful response.
I don't know how to properly set the DATA_DIR path.
Currently, the folder with the datasets is as follows. Where should I set the DATA_DIR path?
I specified the absolute path for the location surrounded by the red frame, but it didn't work.
I confirmed that there is no problem in the correspondence between the training image and the annotated image.
![image](https://user-images.githubusercontent.com/64525148/86558511-7cea0d00-bf94-11ea-877b-aadeeb61217c.png)

**Comment by MaybeShewill-CV** [comment]
@yakubota Eg. The DATA_DIR: "REPO_ROOT_DIR/data/example_dataset/cityscapes" :)

**Comment by yakubota** [comment]
I specified the absolute path above and got the same error.
Is this due to the fact that there are only 8 images each of train, test and val in the sample data?

**Comment by MaybeShewill-CV** [comment]
@yakubota The image in data folder is just a sample. You'd better use the whole complete Cityscapes dataset to train the model:)

**Comment by MaybeShewill-CV** [comment]
@yakubota The error you mentioned above refer to a shape mismatch problem. The decode image should have size (2048, 1024) which is the origin image shape in cityscapes dataset. But it seems that the input tensor shape which you put in is with size of (1024, 256). You may check if there is something wrong during your processing:)

**Comment by yakubota** [comment]
The image is sample data, the program has changed only the path specifies of "REPO_ROOT_DIR/config/cityscapes/cityscapes_bisenetv2.yaml".
However, I got the following error. If you know the cause, please help me.

Error:
2020-07-06 19:36:13.516 | INFO     | trainner.cityscapes.cityscapes_bisenetv2_multi_gpu_trainner:train:379 - => Starts to train BiseNetV2 from scratch ...
0it [00:00, ?it/s]
C:\Users\students\anaconda3\envs\seg\lib\site-packages\numpy\core\fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Users\students\anaconda3\envs\seg\lib\site-packages\numpy\core\_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
  0%|                                                                                                                                                                                                                 | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\students\anaconda3\envs\seg\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
    return fn(*args)
  File "C:\Users\students\anaconda3\envs\seg\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\students\anaconda3\envs\seg\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 2097152 values, but the requested shape has 262144
         [[{{node Reshape_1}}]]
         [[graph_input_node/val_IteratorGetNext]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/cityscapes/train_bisenetv2_cityscapes.py", line 40, in <module>
    train_model()
  File "tools/cityscapes/train_bisenetv2_cityscapes.py", line 32, in train_model
    worker.train()
  File "C:\Users\students\Desktop\bisenetv2-tensorflow-master\tools\cityscapes\trainner\cityscapes\cityscapes_bisenetv2_multi_gpu_trainner.py", line 432, in train
    self._val_loss, self._val_global_step
  File "C:\Users\students\anaconda3\envs\seg\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)
  File "C:\Users\students\anaconda3\envs\seg\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\students\anaconda3\envs\seg\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)
  File "C:\Users\students\anaconda3\envs\seg\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 2097152 values, but the requested shape has 262144
         [[{{node Reshape_1}}]]
         [[graph_input_node/val_IteratorGetNext]]
![image](https://user-images.githubusercontent.com/64525148/86584691-44602880-bfc0-11ea-80df-f62749cfdc4e.png)

**Comment by MaybeShewill-CV** [comment]
@yakubota ==! Still you have wrongly setup your config file. The REPO_ROOT_DIR should be your repo's root dir eg. D:\\lanenet-detection-master rather than "REPO_ROOT_DIR". Please paste your config yaml file here and make sure you have successfully generated the tfrecords. Your problem was not that hard to solve if you have a little knowledge about what you did here:)

**Comment by yakubota** [comment]
tfrecords has been successfully generated.
The DATA_DIR, TEST_FILE_LIST, TRAIN_FILE_LIST and VAL_FILE_LIST specified in that file "cityscapes_bisenetv2.yaml"" are as follows.
Can you tell me what is wrong with it?

DATA_DIR: 'C:\Users\students\Desktop\bisenetv2-tensorflow-master\data\example_dataset\cityscapes'
TEST_FILE_LIST: 'C:\Users\students\Desktop\bisenetv2-tensorflow-master\data\example_dataset\cityscapes/image_file_index/test.txt'
TRAIN_FILE_LIST: 'C:\Users\students\Desktop\bisenetv2-tensorflow-master\data\example_dataset\cityscapes/image_file_index/train.txt'
VAL_FILE_LIST: 'C:\Users\students\Desktop\bisenetv2-tensorflow-master\data\example_dataset\cityscapes/image_file_index/val.txt'

![image](https://user-images.githubusercontent.com/64525148/86590375-74acc480-bfca-11ea-8c5d-f15d5fdfb8a7.png)

**Comment by MaybeShewill-CV** [comment]
@yakubota I have tested it on my local machine. Nothing wrong happened. I did not know how you reach the problem. You'd better check if there are any problems with image shape during your process. And still I recommend you to use the whole cityscapes dataset to train. The config yaml file was made for the whole cityscapes dataset rather than the toy example instead. Good luck :)

**Comment by yakubota** [comment]
I downloaded the dataset from cityscapes and revalidated it, but the results were no good.
I try to find the cause.

When executing tools/cityscapes/train_bisenetv2_ cityscapes.py, CUDA_VISIBLE_DEVICES="0, 1, 2, 3" in README.md is not required?

Here's the execution I'm typing in
python tools/cityscapes/train_bisenetv2_ cityscapes.py

**Comment by MaybeShewill-CV** [comment]
@yakubota If you have four gpus and intend to use all of them you do not have to set CUDA_VISIBLE_DEVICES="0, 1, 2, 3". CUDA_VISIBLE_DEVICES="0, 1, 2, 3" was used to specify certain some of your gpus which you want to use otherwise tensorflow will allocate all of them instead:)

**Comment by yakubota** [comment]
I understand. Thank you.
