### ISSUE TITLE
Poor inference result

### ISSUE THREAD

**Issue by umairanis03** [MaybeShewill-CV/bisenetv2-tensorflow#18]
Hi @MaybeShewill-CV 
Thanks for your amazing work.

I tested your pre-trained model on the images in the repository, it works well. Unfortunately, on other images, it performs poorly.

**Comment by MaybeShewill-CV** [comment]
@umairanis03 What do you mean other images?

**Comment by umairanis03** [comment]
@MaybeShewill-CV I mean images, not from CityScapes dataset

**Comment by MaybeShewill-CV** [comment]
@umairanis03 The model was trained with cityscapes dataset so what you mentioned above was quite normal in my opinion:)
