### ISSUE TITLE
more detailed guideline

### ISSUE THREAD

**Issue by Shelfcol** [MaybeShewill-CV/bisenetv2-tensorflow#2]
Thank you for your invitation. I am new to deeplearning, and I know little about this field. I just want to implement semantic segmentation in my reasearch,  not  to explore in depth. Could you please show the accuracy about your codes experimented on cityscapes dataset, and give me more specified introduction to use your codes? Looking forward to your reply.

**Comment by MaybeShewill-CV** [comment]
@Shelfcol Detailed README file will be uploaded soon:)

**Comment by Shelfcol** [comment]
Looking forward to it very much. Waiting for your good news

**Comment by MaybeShewill-CV** [comment]
@Shelfcol You may check README file now:)
