### ISSUE TITLE
A question about GFLops

### ISSUE THREAD

**Issue by Flyzanetothesky** [MaybeShewill-CV/bisenetv2-tensorflow#24]
the GFLops of Paper is 21.15 with the input of spatial size is 2048 x 1024, but why your GLops is 34.53 ??? @MaybeShewill-CV

 
![Screenshot from 2020-09-15 14-56-17](https://user-images.githubusercontent.com/26514628/93176872-7fbb6800-f764-11ea-94f7-c95e090b3f8e.png)

**Comment by MaybeShewill-CV** [comment]
@Flyzanetothesky Maybe some difference between my implementation and official implementation:)

**Comment by Flyzanetothesky** [comment]
> @Flyzanetothesky Maybe some difference between my implementation and official implementation:)

thanks for your quickly response,  I wonder your input size of model when you calculate GFLops , 2048x1024 or others ?

**Comment by MaybeShewill-CV** [comment]
@Flyzanetothesky https://github.com/MaybeShewill-CV/bisenetv2-tensorflow/blob/34ba8e7e939efa387188510f9eb74cd27f260a8a/tools/cityscapes/timeprofile_cityscapes_bisenetv2.py#L291-L302 
Graphy's input tensor size was [512, 1024]
