### ISSUE TITLE
ModuleNotFound when testing

### ISSUE THREAD

**Issue by JJavierga** [MaybeShewill-CV/bisenetv2-tensorflow#26]
When I try to run the test I get an error saying:

 File "tools/cityscapes/test_bisenetv2_cityscapes.py", line 21, in <module>
    from local_utils.config_utils import parse_config_utils
ModuleNotFoundError: No module named 'local_utils'

It looks like it is unable to link to the directory where local_utils is.

Any idea?

**Comment by MaybeShewill-CV** [comment]
@JJavierga add repo's root path to your PYTHONPATH
