### ISSUE TITLE
About  train miou and val miou

### ISSUE THREAD

**Issue by Flyzanetothesky** [MaybeShewill-CV/bisenetv2-tensorflow#27]
Hi @MaybeShewill-CV , I had been finished model-training, and evaluated my model on the whole cityscapes validation dataset used your train code and val code with no changes. But i have a problem why train miou only achieve 0.68 and val miou only achieve 0.53 in the training process, but when I evaluated my model the miou can achieve 71.3 ?  Thanks

the image is train results:

![Screenshot from 2020-09-23 19-42-58](https://user-images.githubusercontent.com/26514628/94010228-3ad4a880-fdd8-11ea-94fe-caf229f3e87d.png)
this one is the results of evaluate on whole validation dataset:
![Screenshot from 2020-09-22 20-50-38](https://user-images.githubusercontent.com/26514628/94010388-77080900-fdd8-11ea-90d2-37a93f8dbebe.png)

**Comment by MaybeShewill-CV** [comment]
@Flyzanetothesky During training process the iou was computed within a batch of data and no moving avg was applied here. During eval the miou was computed within the whole validation dataset:)

**Comment by Flyzanetothesky** [comment]
@MaybeShewill-CV yeah, I know, the batch size of evaluation is 4.`https://github.com/MaybeShewill-CV/bisenetv2-tensorflow/blob/c750f3247def2f0738ee9daec89d306317589b61/config/cityscapes/cityscapes_bisenetv2.yaml#L57`
