### ISSUE TITLE
about training new custom data set

### ISSUE THREAD

**Issue by zjj321** [MaybeShewill-CV/bisenetv2-tensorflow#29]
I have trained new data set it worked and successful and all imag is resize 960*540。

but when i try to train  smaller dataset:  every img is 896 * 544, it is always print error:slice index 262144 of dimension 0 out of bounds。and i changed even smaller image size: 512*320, it print same error。

somewhere should i need to do?

**Comment by MaybeShewill-CV** [comment]
@zjj321 Change the config here https://github.com/MaybeShewill-CV/bisenetv2-tensorflow/blob/710db8646ceb505999b9283c0837c0b5cf67876d/config/cityscapes/cityscapes_bisenetv2.yaml#L80-L83
You may change it into 0.5 * 896 * 544 or 0.25 * 896 * 544

**Comment by zjj321** [comment]
best wishs,thank you so much
