### ISSUE TITLE
train my custom data

### ISSUE THREAD

**Issue by zhangyunming** [MaybeShewill-CV/bisenetv2-tensorflow#3]
hi, it is a good joob!

when i tainning my own data , the data that are not in same sizes, translate the data to tfrecords successed, and then trained it turns:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 518400 values, but the requested shape has 262144.

question: how to train custom data and the trainning data must in same size as cityscapes in (2048,1024)?

thanks

**Comment by MaybeShewill-CV** [comment]
@zhangyunming All your training samples should have the same size. And you may adjust config/*.yml file to your dataset's image shape:)

**Comment by zhangyunming** [comment]
when i  resize all my trainning images and labels to same size, it is ok.

there  are two classes :background 0 and 1 . i see you ignore  0 and 255 ,  so the class=1?
i delete the ignore=0 , and class=2?

**Comment by MaybeShewill-CV** [comment]
@zhangyunming 
<img width="684" alt="MacHi 2020-05-13 10-39-57" src="https://user-images.githubusercontent.com/15725187/81765345-274e3280-9506-11ea-92ed-baf3b6343166.png">
Ignore index was defined here. If you want to do a binary segmentation (background vs target) set class_nums=2 then:)
