### ISSUE TITLE
inference time

### ISSUE THREAD

**Issue by CuttlefishXuan** [MaybeShewill-CV/bisenetv2-tensorflow#36]
Thanks for the great work! 
What is the inference time of the BiSeNetV2 model with input size 1024*512?
According to CoinCheung'repo, the speed of v2 is no different than v1 (https://github.com/CoinCheung/BiSeNet/tree/master/tensorrt). So, can anyone reproduce the results of 156fps in the paper?

**Comment by CuttlefishXuan** [comment]
Thanks for the great work! 
What is the inference time of the BiSeNetV2 model with input size 1024*512?
According to CoinCheung'repo, the speed of v2 is no different than v1 (https://github.com/CoinCheung/BiSeNet/tree/master/tensorrt). So, can anyone reproduce the results of 156fps in the paper?

**Comment by MaybeShewill-CV** [comment]
@CuttlefishXuan The inference time can reach 87fps with gtx1070 and trt. With gtx3080 and trt the inference time can reach 170fps:)

**Comment by CuttlefishXuan** [comment]
Woow, it's close to the paper!

**Comment by MaybeShewill-CV** [comment]
@CuttlefishXuan You could test on your local machine and the result may be slicly different due to environment. Welcome to share your test result:)

**Comment by CuttlefishXuan** [comment]
I tested the pretrained model on my local machine which is 1080Ti. But why I get the result of 50.16fps for the bisenetv2 model. And is the default input image size 512×1024? Sorry i am not familiar with tensorflow.

**Comment by MaybeShewill-CV** [comment]
@CuttlefishXuan https://github.com/MaybeShewill-CV/bisenetv2-tensorflow/blob/f55c2e9892077ffe7d5d45c15cba2c51c416a765/tools/cityscapes/timeprofile_cityscapes_bisenetv2.py#L156-L158
Input image was rescaled into 1024*512

**Comment by CuttlefishXuan** [comment]
@MaybeShewill-CV ok, thanks. Than why the result i got is 50fps for bisenetv2 on gtx 1080ti, is there something I missed?

**Comment by MaybeShewill-CV** [comment]
@CuttlefishXuan Not caused by the code here. Maybe something wrong with your local env:)

**Comment by CuttlefishXuan** [comment]
@MaybeShewill-CV OK, thanks again for your patience.

**Comment by MaybeShewill-CV** [comment]
@CuttlefishXuan Welcome:)
