### ISSUE TITLE
请教一下为什么训练时GPU使用率才百分之几

### ISSUE THREAD

**Issue by dgliu123** [MaybeShewill-CV/bisenetv2-tensorflow#40]
请教一下为什么训练时GPU使用率才百分之几
![FCDCD52E-1655-47e0-AE8C-B975E4C642BF](https://user-images.githubusercontent.com/80246691/110292180-c5782f80-8027-11eb-914c-530ba3bbaa52.png)

**Comment by MaybeShewill-CV** [comment]
@dgliu123 你在用cpu训练 检查你的tensorflow-gpu环境哪里有问题吧

**Comment by dgliu123** [comment]
确定安装得有问题,已经 解决,谢谢

> @dgliu123 你在用cpu训练 检查你的tensorflow-gpu环境哪里有问题吧

确定安装得有问题,已经 解决,谢谢

**Comment by MaybeShewill-CV** [comment]
@dgliu123 好的：）
