### ISSUE TITLE
训练时，Train loss: nan Train miou: nan

### ISSUE THREAD

**Issue by Yulian-Xie** [MaybeShewill-CV/bisenetv2-tensorflow#41]
![image](https://user-images.githubusercontent.com/26408500/110727980-33566e00-8257-11eb-88e4-85d57941b89d.png)

**Comment by MaybeShewill-CV** [comment]
@Yulian-Xie 我猜测还是数据集的问题 检查下你的数据有没有问题 标签数据读入之后数据有没有被污染

**Comment by Yulian-Xie** [comment]
嗯，是数据集数量太少了

**Comment by MaybeShewill-CV** [comment]
@Yulian-Xie ok:)
