### ISSUE TITLE
Could you share your released bisenetv2 model in baidu or google cloud?

### ISSUE THREAD

**Issue by jacob081** [MaybeShewill-CV/bisenetv2-tensorflow#46]
RT

**Comment by MaybeShewill-CV** [comment]
@jacob081 I will see if it can be uploaded on google cloud:)

**Comment by jacob081** [comment]
> @jacob081 I will see if it can be uploaded on google cloud:)

Thanks, wait for good news :)

**Comment by MaybeShewill-CV** [comment]
@jacob081 I failed using google cloud ==!
