### ISSUE TITLE
Quantized Model?

### ISSUE THREAD

**Issue by dragonvenenoso** [MaybeShewill-CV/bisenetv2-tensorflow#48]
Hi,

I am trying to use the trained model in my TPU, so I need to quantize the model (using TF1).

I think I must add the line `contrib_quantize.create_training_graph(input_graph=self._sess.graph, quant_delay=0)` inside the `__init__` function of the file `BiseNetV2CityScapesTrainer.py`. However it is a bit unclear to me exactly where .

Would you have any recommendation?
Thanks

**Comment by MaybeShewill-CV** [comment]
@dragonvenenoso Sry doesn't have any experience in tf quant:)

**Comment by dragonvenenoso** [comment]
Thanks for the answer. Yes... TF1 Quant is a nightmare

**Comment by MaybeShewill-CV** [comment]
@dragonvenenoso I will keep you informed if I get something valuable:)
