### ISSUE TITLE
请教模型几个参数的作用

### ISSUE THREAD

**Issue by dgliu123** [MaybeShewill-CV/bisenetv2-tensorflow#49]
你好,请问以下几个参数的作用是什么
 GE_EXPAND_RATIO: 6
        SEMANTIC_CHANNEL_LAMBDA: 0.25
        SEGHEAD_CHANNEL_EXPAND_RATIO: 2

**Comment by MaybeShewill-CV** [comment]
@dgliu123 各个模块通道扩展或者缩减的比例，详细解释可以看下论文:)
