### ISSUE TITLE
请教一下cityscapes数据集预处理的问题

### ISSUE THREAD

**Issue by comic666** [MaybeShewill-CV/bisenetv2-tensorflow#5]
对于训练集图片：
1.先随机水平翻转
2.然后对图片进行随机尺度的缩放，{ 0.75, 1, 1.25, 1.5, 1.75, 2.0}
3.随机裁剪为512x1024
4.归一化操作和Normalize
以上操作除了4，标签采用相同的操作。
对于验证集图片：
1.将图片缩小为512x1024，标签不变化
2.归一化操作和Normalize
最后将预测结果邻近插值为标签大小，计算miou。
不知道我的理解有没有问题，希望作者能够指教一下。我用pytorch实现的代码最多也就60%的miou。不知道是哪里出了问题

**Comment by MaybeShewill-CV** [comment]
@comic666 是这样的 只是augmentation的顺序我这边是 1.resize 2.mirror 3.random crop 4.normalize

**Comment by comic666** [comment]
> @comic666 是这样的 只是augmentation的顺序我这边是 1.resize 2.mirror 3.random crop 4.normalize

好的多谢啦。还有一个问题论文中提到Segmentation Head，中间有个参数Ct,这个取的是固定值64么。

**Comment by MaybeShewill-CV** [comment]
@comic666 
<img width="345" alt="image" src="https://user-images.githubusercontent.com/15725187/82124422-87c4c480-97d1-11ea-8e2a-4d8b6fcfbfbb.png">
是按照一个固定的比例增大的 不是固定的某个值. 具体可以查看论文：）

**Comment by Soulempty** [comment]
@comic666 ，你目前miou多少呢？如何初始化权重的？我用pytorch大概66左右，借用了semseg开源代码

**Comment by comic666** [comment]
> @comic666 ，你目前miou多少呢？如何初始化权重的？我用pytorch大概66左右，借用了semseg开源代码

目前只有60.5%，能不能交流一下呀。加个好友啥的
