### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by kkycj** [MaybeShewill-CV/bisenetv2-tensorflow#7]
Hello, I tried the test model on my computer(GTX 1070), but I found the mean fps is only 14.
So I run the time profile tools to test the performance. Then the error went out.
I'm not familiar with tensorflow and segmentation. Could you tell me how to fix this problem?

Here is the error information:

Trt engine file: ./checkpoint/bisenetv2_cityscapes_frozen.trt has been generated
WARNING:tensorflow:From tools/timeprofile_bisenetv2.py:90: calling import_graph_def (from tensorflow.python.framework.importer) with op_dict is deprecated and will be removed in a future version.
Instructions for updating:
Please file an issue at https://github.com/tensorflow/tensorflow/issues if you depend on this feature.
Traceback (most recent call last):
  File "tools/timeprofile_bisenetv2.py", line 319, in <module>
    pb_file_path=args.pb_file_path
  File "tools/timeprofile_bisenetv2.py", line 157, in time_profile_tensorflow_graph
    image_feed = image[:, :, (2, 1, 0)]
TypeError: 'NoneType' object is not subscriptable

By the way, I'm searching for a segmentation model as the preprocess of a semantic slam system.
Can I deploy your work with tensorflow framework to the project just like what PaddlePaddle do?
Thank you.

**Comment by MaybeShewill-CV** [comment]
@kkycj 1.No image loaded in your testing process. Check if you have input the right image file path. 2. Sorry I did not get your intention. What do you mean by deploy tf just like what paddle paddle do? :)

**Comment by kkycj** [comment]
@MaybeShewill-CV Thank you for your reply.
1. I noticed that I copied the command in README.md,as
 `python tools/timeprofile_bisenetv2.py --input_image_path ./data/test_data/test_01.png` 

where `./data/test_data/test_01.png` should be `./data/test_img/test_01.png`. And I solved this.

2.I'm sorry I didn't explain my propose clearly. I'm trying to combine the segmentation programme with a slam system written by C++. As far as I known, PaddleSeg provide a way to export the model by C++ and deploy it in user's own project. I just want to know how can I achieve that in this case.

**Comment by MaybeShewill-CV** [comment]
@kkycj 1.Thanks for correction. 2. TensorFlow also support cpp inference and you may google how to use it. 3. Other framework such as MNN or NCNN also can achieve what you want. 4. I have uploaded a tool to convert the pb model into tensorrt engine and you may use TensorRT to deploy the model. 5. PaddlePaddle have a useful tool named X2Paddle(or something like this) which may help you to convert the model from other framework into Paddle format. :)

**Comment by kkycj** [comment]
@MaybeShewill-CV Thank you for your help. I greatly appreciate it!

**Comment by MaybeShewill-CV** [comment]
@kkycj Welcome:)
