### ISSUE TITLE
Hello, when I run your code, the following problems always appear, how can I solve it? Looking forward to your reply, thank you very much

### ISSUE THREAD

**Issue by xiaomixiaomi123zm** [MaybeShewill-CV/bisenetv2-tensorflow#9]
Hello, when I run your code, the following problems always appear, how can I solve it? Is it a problem during packaging?Looking forward to your reply, thank you very much.

ModuleNotFoundError: No module named 'trainner'
ModuleNotFoundError: No module named 'local_utils'

**Comment by MaybeShewill-CV** [comment]
@xiaomixiaomi123zm add project folder python to your PYTHONPATH environment vars:)

**Comment by xiaomixiaomi123zm** [comment]
Hello, I am running on thelinux  server, how do I add it? Is it convenient for you, can you add my QQ：907675183  guide me? thank you very much~ @MaybeShewill-CV

**Comment by MaybeShewill-CV** [comment]
@xiaomixiaomi123zm export PYTHONPATH=文件夹路径:{$PYTHONPATH}

**Comment by xiaomixiaomi123zm** [comment]
Thank you very much for your help, it has been solved.
 However, the following problems arise, how should this be handled? @MaybeShewill-CV 

OSError: Config file: ./config/cityscapes_bisenet.yaml, can not be read

**Comment by MaybeShewill-CV** [comment]
@xiaomixiaomi123zm run your command in project's root path. The config file path is the relative path to project's root path.

**Comment by xiaomixiaomi123zm** [comment]
Thank you for your guidance, I have now run successfully.

**Comment by MaybeShewill-CV** [comment]
@xiaomixiaomi123zm Welcome:)
